name: Documentation

on:
  push:
    branches:
      - main # update to match your development branch (master, main, dev, trunk, ...)
    tags: '*'
  pull_request:

jobs:
  build:
    permissions:
      actions: write
      contents: write
      statuses: write
    runs-on: ubuntu-latest
    env:
      PYTHON: ""
    steps:
      - uses: actions/checkout@v4
      - name: "Manually add Conda.jl folder due to bug in its build step" # https://github.com/JuliaPy/Conda.jl/issues/251
        run: |
          mkdir -p "/home/runner/.julia/conda/3/x86_64"
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}